Hongmh 12 4th
syg4806/st102-personal-sprint pull request #14
Opened 2020-12-27 15:37 UTC by myeongheonhong

쉬운문제들이지만 기초부터 천천히!

2021-01-08 12:12 UTC, syg4806 requested changes
ex2 만 다시 확인해줘여

2021-01-08 12:12 UTC, syg4806 commented on CodingTest/hongmh/2020_12_4th/src/ex1/ex2.java
> +}
이 문제 이걸로 풀려요?

2021-01-08 12:12 UTC, syg4806 commented on CodingTest/hongmh/2020_12_4th/src/ex1/ex3.java
> + 		   return false;
요부분 필요없지않을까?

2021-01-08 12:12 UTC, syg4806 commented on CodingTest/hongmh/2020_12_4th/src/ex1/ex4.java
> +    }
```java
int start = s.length()/2;
int end = start
if(s.length()%2 == 0)        end++;
return s.substring(half,end);
```
이런식으로 하면 조금더 보기 좋지 않을까 싶습니당
중복되는 코드가 있다면 어떻게 줄일 수 있을까 고민해보기를!

2021-01-09 15:05 UTC, myeongheonhong commented on CodingTest/hongmh/2020_12_4th/src/ex1/ex3.java
> + 		   return false;
만약 시작하는 식이 )로 시작하면 무조건 식이 틀린식이 되므로 반복문을 돌지않아도 된다는 생각에 조건문을 넣어봤습니다!!

2021-01-09 15:10 UTC, myeongheonhong commented on CodingTest/hongmh/2020_12_4th/src/ex1/ex2.java
> +}
네!! 효율성테스트에서도 문제없이 통과했습니다!

2021-01-09 15:12 UTC, merged